### ISSUE TITLE
[BUG]attempt to index a nil value (global 'lib')

### ISSUE THREAD

**Issue by l3oncoder** [Qbox-project/qb-core#18]
### Summary

attempt to index a nil value (global 'lib')

### Reproduction

1. okok-vehicleshop
2. Open vehicle menu
3. nothing happens
4. attempt to index a nil value (global 'lib')

### Expected behavior

Menu should open, and should be able to browse cars.

### Actual behavior

[BUG]attempt to index a nil value (global 'lib')

### Additional context

Up into the recent update that was posted 8hours prior to this bug report,  Everything been working flawlessly to what I can tell.

Also Advanced Drugs Creator 4.6 by jaksam1074, Is having same issue walk up to a blip and click E and same error, I believe this is to do with QB:Notify

### Last Updated

today

### Custom Resources

okok-vehicleshop

### Resource Rename

no

**Comment by ihyajb** [comment]
what’s the start order of your scripts? `ox_lib` needs to start before `qb-core`.

**Comment by l3oncoder** [comment]
# QBCore & Extra stuff
ensure qb-core
ensure ox_lib
ensure ox_target
ensure [ox]
ensure [qb]
ensure [standalone]
ensure [voice]

The order that was provided in the server.cfg

**Comment by D4isDAVID** [comment]
Looks like we need to update it...

**Comment by l3oncoder** [comment]
Thanks guys much love working :D
