### ISSUE TITLE
[SUGGESTION] notify

### ISSUE THREAD

**Issue by l3oncoder** [Qbox-project/qb-core#23]
### The problem

Hi there, So far QBox has been awesome for us, However No matter what position setting I put in the config.lua the notifications seem to default to top right, I was wonder if this is just incomplete? Also an option for button center would be amazing

### Ideal solution

More position options for qb:notify

**Comment by Manason** [comment]
Looks like I forgot to connect the config setting to the actual notification code. Will fix shortly. The six options are top left|middle|right and bottom left|middle|right. Is this what you mean by wanting a center button, or are you referring to something else?

**Comment by l3oncoder** [comment]
Yeah sorry made a typo and that perfect thanks
