### ISSUE TITLE
[BUG] ox_doorlock

### ISSUE THREAD

**Issue by l3oncoder** [Qbox-project/qb-core#30]
### Summary

No framework

### Reproduction

Update framework

### Expected behavior

Compatible framework to be loaded

### Actual behavior

[script:ox_doorlock:w] Warning: no compatible framework was loaded, most features will not work

### Last Updated

today

### Custom Resources

others

### Resource Rename

no

**Comment by Manason** [comment]
This should have been fixed in version 1.8.5. https://github.com/overextended/ox_doorlock/issues/114

**Comment by l3oncoder** [comment]
Fix Thanks dude @Manason
